version: '3'

tasks:
  default:
    desc: Default task
    cmds:
      - task: dev

  build:
    desc: Build the application
    cmds:
      - go build -o pr-toolbox-go .

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f pr-toolbox-go

  deps:
    desc: Install dependencies
    cmds:
      - go mod tidy

  templ:
    desc: Generate templ files
    cmds:
      - templ generate

  dev:
    desc: Run with Air for hot reloading
    cmds:
      - air

  db:migrate:
    desc: Run database migrations
    cmds:
      - goose sqlite3 ./data/pr_toolbox.db -dir ./migrations up

  db:rollback:
    desc: Rollback last migration
    cmds:
      - goose sqlite3 ./data/pr_toolbox.db -dir ./migrations down

  db:status:
    desc: Show migration status
    cmds:
      - goose sqlite3 ./data/pr_toolbox.db -dir ./migrations status

  db:reset:
    desc: Reset database (drop all tables and re-run migrations)
    cmds:
      - rm -f ./data/pr_toolbox.db
      - goose sqlite3 ./data/pr_toolbox.db -dir ./migrations up
