version: '3'

tasks:
  default:
    desc: Default task
    cmds:
      - task: dev

  build:
    desc: Build the application
    cmds:
      - go build -o pr-toolbox-go .

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f pr-toolbox-go

  deps:
    desc: Install dependencies
    cmds:
      - go mod tidy

  templ:
    desc: Generate templ files
    cmds:
      - templ generate

  dev:
    desc: Run with Air for hot reloading
    cmds:
      - air
