// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func IndexPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = BaseLayout(PageData{
			Title:       "People Management",
			Description: "People Management System",
			Content:     IndexContent(),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func IndexContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-6xl mx-auto bg-white rounded-xl shadow-2xl overflow-hidden\"><div class=\"bg-gradient-to-br from-primary-500 to-purple-600 text-white p-8 text-center\"><h1 class=\"m-0 text-4xl font-light\">People Management System</h1></div><div class=\"p-8\"><!-- Navigation --><div class=\"mb-6\"><a href=\"/pr_descriptions\" class=\"text-primary-500 hover:text-primary-600 font-medium\">📝 PR Descriptions →</a></div><div class=\"mb-8 flex gap-4 items-center flex-wrap\"><a href=\"/api/people\" x-target=\"people-data\" class=\"px-6 py-3 border-none rounded-lg cursor-pointer text-sm font-medium transition-all duration-300 bg-primary-500 text-white hover:bg-primary-600 hover:-translate-y-0.5 no-underline inline-block\">Load People</a> <a href=\"/health\" x-target=\"health-status\" class=\"px-6 py-3 border-none rounded-lg cursor-pointer text-sm font-medium transition-all duration-300 bg-gray-600 text-white hover:bg-gray-700 hover:-translate-y-0.5 no-underline inline-block\">Check Health</a><div id=\"health-status\" class=\"px-4 py-2.5 rounded-lg font-medium\" x-show=\"$el.innerHTML.trim() !== ''\" x-html=\"$el.innerHTML\"></div></div><div id=\"health-status\"></div><div id=\"people-data\"><!-- People data will be loaded here via Alpine AJAX --></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
